repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.0
    hooks:
      - id: python-safety-dependencies-check
  - repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.25.2
    hooks:
      - id: pyupgrade
        args: ['--py37-plus']
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-added-large-files  # prevent large files from being added
      - id: check-ast  # verify python syntax by building ASTs
      - id: check-merge-conflict  # check for pending merge conflicts
      - id: debug-statements  # check for debugger imports
      - id: detect-private-key  # prevent committing private keys
      - id: end-of-file-fixer  # all files must end with one newline
      - id: fix-encoding-pragma  # remove magic "coding" lines
        args: ['--remove']
      - id: trailing-whitespace  # fix trailing whitespace
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [
          '-e', 'git+https://github.com/pycqa/pyflakes@1911c20#egg=pyflakes',
          '-e', 'git+https://github.com/pycqa/pycodestyle@d219c68#egg=pycodestyle',
        ]
